esphome:
  name: led-strip

esp8266:
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret fallback_ssid
    password: !secret fallback_password


web_server:
  port: 80

logger:
  level: DEBUG

api:
  password: ""

ota:
  password: ""

status_led:
  pin:
    number: GPIO2
    inverted: true

light:
  - platform: rgbww
    name: "LED strip"
    red: red_channel
    green: green_channel
    blue: blue_channel
    cold_white: cold_white_channel
    warm_white: warm_white_channel

output:
  - platform: esp8266_pwm
    id: red_channel
    pin: GPIO14
  - platform: esp8266_pwm
    id: blue_channel
    pin: GPIO13
  - platform: esp8266_pwm
    id: green_channel
    pin: GPIO12
  - platform: esp8266_pwm
    id: cold_white_channel
    pin: GPIO15
  - platform: esp8266_pwm
    id: warm_white_channel
    pin: GPIO5
