esphome:
  name: solar-charger-monitor

esp8266:
  board: esp8285

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "***REMOVED***"
  password: "***REMOVED***"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ***REMOVED***
    password: "***REMOVED***"

captive_portal:

external_components:
  - source: github://KinDR007/VictronMPPT-ESPHOME@main

uart:
  id: uart0
  tx_pin: GPIO4  # Not used! The communication is read-only
  rx_pin: GPIO2
  baud_rate: 19200
  rx_buffer_size: 256

victron:
  id: victron0
  uart_id: uart0
  throttle: 20s

sensor:
  - platform: victron
    victron_id: victron0
    panel_voltage:
      name: "Panel voltage"
    battery_voltage:
      name: "Battery voltage"
    battery_current:
      name: "Battery current"

   
