
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

owntracks:

recorder:
  purge_keep_days: 720
  auto_purge: true
  db_url: !secret mysql_db

# This allows recording of location which comes as attributes from the OwnTracks integration.
template:
  - sensor:
      name: "Camper Latitude"
      state: '{% if state_attr("device_tracker.camper_bonito", "latitude") %}{{ ((state_attr("device_tracker.camper_bonito", "latitude"))) | float }}{% endif %}'
  - sensor:
      name: "Camper Longitude"
      state: '{% if state_attr("device_tracker.camper_bonito", "longitude") %}{{ ((state_attr("device_tracker.camper_bonito", "longitude"))) | float }}{% endif %}'
  - sensor:
      name: "Camper GPS Accuracy"
      state: '{% if state_attr("device_tracker.camper_bonito", "gps_accuracy") %}{{ ((state_attr("device_tracker.camper_bonito", "gps_accuracy"))) | float }}{% endif %}'
